### PR TITLE
Adding some documentation for SSO options

### PR DESCRIPTION
**Pull request by jakkarth**
- Added README.md section for configuring OAuth2
- Added README.md section for configuring SAML
- Added missing env vars to default_env
- Added note about running without SSL termination
- Added sample non-SSL docker compse file

### CODE REVIEW

**Comment by jakkarth** [comment]
Note that `OAUTH_LOGIN_PROVIDER_NAME` and `SAML_LOGIN_PROVIDER_NAME` aren't yet supported in the latest Loomio docker image, since the change to use them was on December 18th and no new Loomio docker image has been created since then.

**Comment by robguthrie** [comment]
Thank you for this thoughtful PR. Nice work.

My only concern is that if we add an additional docker-compose example, it will become outdated when the main file changes.

Additionally, I can't easily see what the differences between the two files are. 

Would you be happy to just remove that additional docker-compose and explain what sections someone would need to delete to disable the proxy?

**Comment by jakkarth** [comment]
The only difference between the files is that one has the nginx sections removed. I explained that in the README.md change, but I can see how that could be confusing. PR updated to have more clear language in the README around that procedure and to remove the second compose file. Is this better?

**Comment by robguthrie** [comment]
I was going to just merge, but if you don't mind me thinking out loud a little more... I will suggest this:

There is a lot of detail for each setting for SAML and OAUTH, and people will need it when they're editing their config file.

So why don't we put all the detailed explanations of those config settings (thank you, by the way!) into the default_env, and then in the README link to that file, so people who generated their env before the default_env was updated will find it.

It also removes some duplication of effort between the readme and default_env.

**Comment by jakkarth** [comment]
My thinking was that the README.md file has nice formatting and longform explanations, while the default_env just has section headers and example values. To be sure I understand, your suggesting taking the longform explanations and adding them as additional comment lines in the default_env file, removing them from the README.md file, and adding a note in README.md pointing out that OIDC and SAML config options can be enabled/configured after the .env file is created? Do I have that right? If so, I'm not necessarily opposed to it, but I do kinda feel like documentation should be in the documentation file rather than as a comment in a config file. That may just be me though, and if you prefer it in default_env I can do that.

**Comment by robguthrie** [comment]
In 2024 I resolve to aim for good enough and let people contribute without spending excess energy. Let's merge it and we can always change it later.

I'm pleased you've shown up and would love to learn more about how/where you're using Loomio.

**Comment by jakkarth** [comment]
Hooray for good enough! The perfect is the enemy of the good :) that's something I've been working on myself.

I'm in the Southeastern US, the leader of a ragtag volunteer group that provides first aid services for pop culture conventions. We grew into the organization structure modeled for us by first response services, specifically because a lot of us work on ambulances for our day job. It's been pretty hierarchical, and that's caused us some trouble internally. I acknowledge that I'm ultimately responsible for the culture our group has, and I'm looking for ways to do better. Consensus building tools like Loomio are one part of that equation for me: helping more people have more voice in the decisions of the group.

Thank you for the work you continue to do to keep Loomio running and growing. Interacting with you has been quite enjoyable! Often open source projects are run by people with great code skills but not-so-great community building skills, and I think to be successful they need both. I shouldn't be surprised that Loomio stands out in that regard compared to other FLOSS contributions I make. I hope the new year treats you well!

**Pull request merged**
